name: Test using Meeshkan

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel deployment
        uses: mskelton/wait-for-vercel-action@v1
        with:
          prod-url: legacy-webapp.vercel.app
          token: ${{ secrets.VERCEL_TOKEN }}
      - name: Run after deployment
        run: echo "Deployment at ${ENVIRONMENT_URL}"
        env:
          ENVIRONMENT_URL: ${{ steps.wait-for-vercel.outputs.url }}
